### ISSUE TITLE
Further enhancements required to fully match windows 10 style

### ISSUE THREAD

**Issue by musm** [InsanityDevice/Dark-10-theme-for-Google-Chrome#1]
![image](https://user-images.githubusercontent.com/4319522/49047904-e7c34780-f1a6-11e8-8bf6-15f5fdf8d738.png)

It should look like the above

Is it possible to set the color to adapt to the background page of the website. White webpages use the white scroll bar, and for dark webpages use the dark scroll bar?

**Comment by mechagomizilla** [comment]
I think it's possible, but not in a surefire way.
There are multiple different scrollbar designs in Windows 10, but I chose the File Explorer variant.
I did mean to create a slightly thinner version of it, but the buttons aren't there mainly because I couldn't bother and settled with the version I wanted to use for myself. Please take note that I'm a student and that I'm insanely busy right now. It will take some time, but I plan to add the following customization options:

* color
* size
* buttons (yes/no)

I need to make an image file for each button variant (4 directions + 3 states = 12 different images), and then figure out if they can be resized or if I need to remake them for each supported size (large, medium, maybe small).
Anyway, it's coming at some point and it would be a miracle if I manage to finish that in the coming weeks.
The automatic lightswitch is last in my priority list (if it's doable) and will also be optional.

**Comment by mechagomizilla** [comment]
For the record, I did originally write that I only meant to reproduce the colour scheme, both on userstyles and in the readme.

**Comment by mechagomizilla** [comment]
It was easier to do than I thought.
Version 2.0 is already close to finished.

The light switch requires javascript, which I'm not as good at. I'll see if I can do it next time I'm bored.

**Comment by mechagomizilla** [comment]
@musm 
The scrollbar should now match Windows 10's scrollbar almost perfectly, except for the transition effects, which are not supported and that I don't even like, to be honest.

As for your previous question, I found out how to set the background colour to any website's background colour. All you need to do is set your background colour to transparent (as with any other colour that you wish to set a transparency for). Just update the style to version 2.1.0 and you're set to go!
